name: Build Job
on:
    push:
        branches:
            - main
    pull_request:
        branches:
          - main
permissions:
  contents: read
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4
              with:
                # fetch-depth: 0 ensures the full git history is cloned instead of a shallow clone.
                # This is useful if your build or tests rely on git history, tags, or commits.
                fetch-depth: 0
            - name: Maven Build
              run: mvn install
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: vprofile
                path: target/*.war
            - name: notify if build fails
              if: failure()
              run: echo "Build failed! Please check the logs for details."
    Testing:
        runs-on: ubuntu-latest
        needs: Build
        steps:
            - name: code checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Maven Test
              run: mvn test
            - name: checkstyle
              run: mvn checkstyle:checkstyle
